---
# roles/prometheus/tasks/main.yml

- name: Ensure yum-utils is installed
  yum:
    name: yum-utils
    state: present

- name: Add Prometheus RPM repository (GPG 체크 비활성화)
  yum_repository:
    name: prometheus
    description: Prometheus RPM Release
    baseurl: https://packagecloud.io/prometheus-rpm/release/el/9/$basearch
    gpgcheck: no
    repo_gpgcheck: no
    enabled: yes

- name: Install Prometheus package (GPG 체크 완전 비활성화)
  yum:
    name: prometheus
    state: latest
    update_cache: yes
    disable_gpg_check: yes

- name: Deploy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Enable & start Prometheus service
  service:
    name: prometheus
    enabled: yes
    state: started

