---
# roles/prometheus/tasks/main.yml

- name: Ensure yum-utils is installed
  yum:
    name: yum-utils
    state: present
  become: true

- name: Add Prometheus RPM repository (GPG 체크 비활성화)
  yum_repository:
    name: prometheus
    description: Prometheus RPM Release
    baseurl: https://packagecloud.io/prometheus-rpm/release/el/9/$basearch
    gpgcheck: no
    repo_gpgcheck: no
    enabled: yes
  become: true

- name: Install Prometheus package (GPG 체크 완전 비활성화)
  yum:
    name: prometheus
    state: latest
    update_cache: yes
    disable_gpg_check: yes
  become: true

- name: alert_rules 디렉터리 생성
  file:
    path: /etc/prometheus/alert_rules
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  become: true

- name: 알림 룰 복사
  copy:
    src: alert_rules/alerts.yml
    dest: /etc/prometheus/alert_rules/alerts.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  become: true
  notify: Restart Prometheus

- name: Deploy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  become: true
  notify: Restart Prometheus

- name: Enable & start Prometheus service
  service:
    name: prometheus
    enabled: yes
    state: started
  become: true

