- name: Node Exporter 설치 및 포트 열기
  hosts: node_exporters
  become: true
  vars:
    firewall_ports:
      - 9100
  roles:
    - firewall
    - node_exporter

- name: Prometheus, Alertmanager & Grafana 설치 및 포트 열기
  hosts: monitoring
  become: true
  vars:
    firewall_ports:
      - 9090   # Prometheus
      - 3000   # Grafana
      - 9093   # Alertmanager
    alertmanager_port: 9093
  roles:
    - firewall
    - alertmanager
    - prometheus
    - grafana

