---
# roles/node_exporter/tasks/main.yml

- name: Ensure crypto policy allows SHA1 (LEGACY)
  become: true
  command: update-crypto-policies --set LEGACY
  when: ansible_distribution_major_version == "9"

- name: Force-import Prometheus RPM GPG key
  become: true
  command: rpm --import https://packagecloud.io/prometheus-rpm/release/gpgkey

- name: Add Prometheus RPM repo for node_exporter
  become: true
  yum_repository:
    name: prometheus-node-exporter
    description: Prometheus Node Exporter RPM
    baseurl: https://packagecloud.io/prometheus-rpm/release/el/9/$basearch
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packagecloud.io/prometheus-rpm/release/gpgkey
    enabled: yes

- name: Install node_exporter via yum (GPG 체크 비활성화)
  become: true
  yum:
    name: node_exporter
    state: latest
    update_cache: yes
    disable_gpg_check: yes


- name: Node Exporter server enable now
  become: true
  service:
    name: node_exporter
    enabled: yes
    state: started
