# 1) 의존 툴 설치
- name: Ensure yum-utils installed
  yum:
    name:
      - yum-utils
    state: present

# 2) Grafana YUM 레포 등록
- name: Add Grafana YUM repo
  yum_repository:
    name: grafana
    description: Grafana OSS
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.grafana.com/gpg.key
    enabled: yes

# 3) Grafana 설치
- name: Install Grafana
  yum:
    name: grafana
    state: latest
    update_cache: yes

# 4) 설정 파일 배포
- name: Deploy Grafana config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    mode: '0644'

# 5) 서비스 활성화 및 시작
- name: Enable & start Grafana
  service:
    name: grafana-server
    enabled: yes
    state: started
