---
# roles/grafana/tasks/main.yml

- name: Ensure yum-utils is installed
  yum:
    name: yum-utils
    state: present

- name: Add Grafana YUM repository
  yum_repository:
    name: grafana
    description: Grafana OSS
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.grafana.com/gpg.key
    enabled: yes

- name: Install Grafana package
  yum:
    name: grafana
    state: latest
    update_cache: yes

- name: Deploy Grafana config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: '0644'

- name: Enable & start Grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started

